[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4"
dioxus-web = "0.4"
dioxus-logger = "0.4"
web-sys = { version = "0.3", features = ["Navigator", "Hid", "HidDeviceRequestOptions"] }
wasm-bindgen = "0.2"
js-sys = "0.3"
log = "0.4"
